### ISSUE TITLE
Key Validation Failure Occurring Even With Keys Passed In

### ISSUE THREAD

**Issue by Neosolon** [aws-amplify/amplify-category-api#1169]
Hi, 

I am having an issue with creating a new record due to a ValidationException on the request. 
Below is a simplified Schema:
```
type LineItem
  @model
  @auth(
    rules: [
      { allow: private }
      { allow: groups, groups: ["admin"], operations: [read, create, delete] }
      { allow: owner, ownerField: "ownerId" }
    ]
  ) {
  id: ID
  Category: BudgetCategory!
  SubCategory: String!
  allocation: Float!
  Content: [BudgetCategories]!
  Aggregator: ID! @index(name: "byLineItem")
  ownerId: String! @primaryKey(sortKeyFields: ["Category", "SubCategory"])
}

type LineItemAggregate
  @model
  @auth(
    rules: [
      { allow: private }
      { allow: groups, groups: ["admin"], operations: [read, create, delete] }
      { allow: owner, ownerField: "ownerId" }
    ]
  ) {
  id: ID!
  Name: String! @primaryKey
  LineItems: [LineItem] @hasMany(indexName: "byLineItem", fields: ["id"])
}
type BudgetCategories {
  Home: HomeBudget
}
enum BudgetCategory {
  HOME
  }
  type HomeBudget {
  Rent: Float
  }
```
Mutation Being Executed:
```
mutation MyMutation {
  createLineItem(
    input: {Category: FOOD, SubCategory: "AutoAndTransport", allocation: 3, Aggregator: "81bfb5bd-901d-4cd0-9def-f7ec2e536dd9", ownerId: "3d106bfb-d807-4540-9925-e8c2c7c9650e", Content: {Home: {Rent: 1.5}}}
  ) {
    id
  }
}

```
Expected Behavior:
A LineItem created linked to the specified Aggregator Instance with the specified Content
Exception:
```
Error while executing Local DynamoDB
{
    "version": "2018-05-29",
    "operation": "PutItem",
    "attributeValues": {
        "id": {
            "S": "cb34d37a-ffe1-40db-b01b-43acc5c68648"
        },
        "createdAt": {
            "S": "2023-01-15T02:16:17.961Z"
        },
        "updatedAt": {
            "S": "2023-01-15T02:16:17.961Z"
        },
        "Category": {
            "S": "FOOD"
        },
        "SubCategory": {
            "S": "AutoAndTransport"
        },
        "allocation": {
            "N": "3"
        },
        "Content": {
            "L": [
                {
                    "M": {
                        "AutoAndTransport": {
                            "M": {
                                "AutoInsurance": {
                                    "N": "1.5"
                                },
                                "GasAndFuel": {
                                    "N": "1.5"
                                }
                            }
                        }
                    }
                }
            ]
        },
        "Aggregator": {
            "S": "81bfb5bd-901d-4cd0-9def-f7ec2e536dd9"
        },
        "ownerId": {
            "S": "3d106bfb-d807-4540-9925-e8c2c7c9650e"
        },
        "Category#SubCategory": {
            "S": "FOOD#AutoAndTransport"
        },
        "__typename": {
            "S": "LineItem"
        }
    },
    "condition": {
        "expression": "(attribute_not_exists(#keyCondition1) AND attribute_not_exists(#keyCondition2))",
        "expressionNames": {
            "#keyCondition1": "ownerId",
            "#keyCondition2": "Category#SubCategory"
        }
    },
    "key": {
        "ownerId": {
            "S": "3d106bfb-d807-4540-9925-e8c2c7c9650e"
        },
        "Category#SubCategory": {
            "S": "FOOD#AutoAndTransport"
        }
    }
}
ValidationException: The number of conditions on the keys is invalid
    at Request.extractError (C:\snapshot\repo\build\node_modules\aws-sdk\lib\protocol\json.js:52:27)
    at Request.callListeners (C:\snapshot\repo\build\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\snapshot\repo\build\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\snapshot\repo\build\node_modules\aws-sdk\lib\request.js:686:14)
    at Request.transition (C:\snapshot\repo\build\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\snapshot\repo\build\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\snapshot\repo\build\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\snapshot\repo\build\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\snapshot\repo\build\node_modules\aws-sdk\lib\request.js:688:12)
    at Request.callListeners (C:\snapshot\repo\build\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
    at Request.emit (C:\snapshot\repo\build\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\snapshot\repo\build\node_modules\aws-sdk\lib\request.js:686:14)
    at Request.transition (C:\snapshot\repo\build\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\snapshot\repo\build\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\snapshot\repo\build\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\snapshot\repo\build\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\snapshot\repo\build\node_modules\aws-sdk\lib\request.js:688:12)
    at Request.callListeners (C:\snapshot\repo\build\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
    at callNextListener (C:\snapshot\repo\build\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
    at IncomingMessage.onEnd (C:\snapshot\repo\build\node_modules\aws-sdk\lib\event_listeners.js:380:13)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ValidationException',
  time: 2023-01-15T02:16:17.992Z,
  requestId: '1b385eea-a508-4c34-9b77-8f4a241e5cef',
  statusCode: 400,
  retryable: false,
  retryDelay: 0.23155847149477493
}
```

**Comment by AnilMaktala** [comment]
Hi  @Neosolon 👋, thanks for raising this issue. we are working on reproducing the issue. Could you please run below command and send us the report amplify diagnose --send-report. please refer [here](https://docs.amplify.aws/cli/reference/diagnose/)#

**Comment by AnilMaktala** [comment]
Hey @Neosolon 👋 , Are you still experiencing this issue?

**Comment by huertasdanny** [comment]
Hi, thank you for reaching out. 

I think I ended up modifying/removing the query altogether.
