### ISSUE TITLE
Mock API fails with: TypeError: Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by orome** [aws-amplify/amplify-category-api#1323]

**Comment by josefaidt** [comment]
Hey @orome :wave: thanks for raising this! This appears to be a duplicate of https://github.com/aws-amplify/amplify-category-api/issues/884, can you confirm whether your project has a GraphQL API?

**Comment by orome** [comment]
@josefaidt Yes, I have a GraphQL API and a REST API.

**Comment by josefaidt** [comment]
Hey @orome thanks for clarifying. Unfortunately I am only able to reproduce this when a GraphQL API is not present in the project, but I am taking a deeper look at this 🙂

**Comment by josefaidt** [comment]
Hey @orome can you try re-running the command with `--debug` and post the full output here?

**Comment by orome** [comment]
@josefaidt With `--debug` the output is exactly the same as in the OP.

**Comment by josefaidt** [comment]
Hey @orome thanks for checking. I have a few follow-up questions to better understand the context:

- do you have any resolver overrides applied?
- do you have an existing directory, `amplify/mock-data`? if so can you delete it and retry?
- do you have Java installed?

Additionally, we have a [PR](https://github.com/aws-amplify/amplify-cli/pull/12154) up to resolve this specific error, which should surface the actual error. Would you be open to verifying whether this prints a more helpful error?

```
gh repo clone aws-amplify/amplify-cli
gh pr checkout 12154
nvm use 14
yarn setup-dev
cd /your/project/directory
amplify-dev mock api
```

**Comment by bzwill** [comment]
Also have this problem after calling amplify mock api:

`TypeError: Cannot read property 'stop' of undefined
    at APITest.stop (/snapshot/repo/build/node_modules/@aws-amplify/amplify-util-mock/lib/api/api.js:193:33)
    at APITest.start (/snapshot/repo/build/node_modules/@aws-amplify/amplify-util-mock/lib/api/api.js:156:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async start (/snapshot/repo/build/node_modules/@aws-amplify/amplify-util-mock/lib/api/index.js:18:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/amplify-util-mock/lib/commands/mock/api.js:21:5)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/amplify-util-mock/lib/amplify-plugin-index.js:55:3)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:135:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:33:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:117:5)`
 
 New project with only 1 API endpoint
