### ISSUE TITLE
`amplify mock api` in an uninitialized project throws with a stack trace

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-category-api#1324]
### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

18

### Amplify CLI Version

11.0.0-beta.8

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a	

### Describe the bug

When running `amplify mock api` in an uninitialized project we are presented with an error and stack trace

```
➜  amplify mock api
AmplifyException [EnvironmentNotInitializedError]: Current environment cannot be determined.
    at AmplifyToolkit.getEnvInfo [as _getEnvInfo] (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/get-env-info.js:9:11)
    at getMockDataDirectory (/snapshot/repo/build/node_modules/@aws-amplify/amplify-util-mock/lib/utils/mock-directory.js:51:23)
    at addMockDataToGitIgnore (/snapshot/repo/build/node_modules/@aws-amplify/amplify-util-mock/lib/utils/git-ignore.js:53:82)
    at start (/snapshot/repo/build/node_modules/@aws-amplify/amplify-util-mock/lib/api/index.js:16:40)
    at Object.run (/snapshot/repo/build/node_modules/@aws-amplify/amplify-util-mock/lib/commands/mock/api.js:21:27)
    at Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/amplify-util-mock/lib/amplify-plugin-index.js:55:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:136:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:34:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:116:5) {
  classification: 'ERROR',
  options: {
    message: 'Current environment cannot be determined.',
    resolution: "Use 'amplify init' in the root of your app directory to create a new environment."
  },
  downstreamException: undefined,
  toObject: [Function (anonymous)],
  details: undefined,
  resolution: "Use 'amplify init' in the root of your app directory to create a new environment.",
  code: undefined,
  link: 'https://docs.amplify.aws/cli/project/troubleshooting/'
}
```

### Expected behavior

Error and resolution are clearly presented in red text

```
➜  amplify mock api
AmplifyException [EnvironmentNotInitializedError]: Current environment cannot be determined.
Resolution: Use 'amplify init' in the root of your app directory to create a new environment.
```

### Reproduction steps

1. `amplify init -y`
2. `amplify add api` > GraphQL > accept defaults
3. simulate a fresh git clone `git init; git clean -fXd`
4. `amplify mock api`
5. observe error

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hey @josefaidt, I have successfully replicated the issue following the steps provided above. Therefore, I am flagging this as a bug for the team to investigate further.

**Comment by manaswi223** [comment]
This PR: https://github.com/aws-amplify/amplify-cli/pull/12266 should fix the issue
