### ISSUE TITLE
Unable to deploy Custom Container Images to an API with Amplify

### ISSUE THREAD

**Issue by jerrodalan** [aws-amplify/amplify-category-api#1474]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install @aws-amplify/cli

### If applicable, what version of Node.js are you using?

16.7.0

### Amplify CLI Version

5.3.1

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

Hello I have made countless attempts to deploy a custom docker image to an api with Amplify with no luck. At this point it is either an issue in Amplify, unsupported or I am missing something small. I keep trying to guess what it could be but my deployment keeps failing at the same spot. I've only been able to successfully deploy a container to the api when using the single express template or the express and python docker compose template on **fully managed only**.  Both of these templates fail on Self Managed with an error you can find below.

With my application I am taking a multi-repo approach instead of a monorepo approach. I have a .net 5.0 api in a separate CodeCommit repo connected and deploying directly to a private Amazon ECR with CodePipeline. Following this thread from a previously reported issue that Josef pointed out in the discord group (https://github.com/aws-amplify/amplify-cli/issues/7751#issuecomment-898809424). I setup my docker file to look this:

```
      FROM AccountNumber.dkr.ecr.us-west-2.amazonaws.com/stat-api:latest
      
      ENV PORT=80
      EXPOSE 80
```

And I setup a docker-compose file to look like this:

```
  version: "3.8"

  services:

      statapi:
          build: 
              context: ./tally-stat-api
              dockerfile: Dockerfile 
          container_name: statapi
          restart: unless-stopped
          ports:
              - "8080:80"
```

I can docker-compose up, I can docker build just the image locally completely fine and hit my api and receive real time results from a DB. But deployment always fails.

If I try to deploy with Fully Managed Selected I receive this:

```
CREATE_FAILED      DeploymentAwaiter AWS::CloudFormation::CustomResource Wed Aug 25 2021 03:28:06 GMT-0600 (Mountain Daylight Time) Received response status [FAILED] from custom resource. Message returned: The execution didn't succeed  Logs: /aws/lambda/amplify-statapp-dev-17582-AwaiterCustomCompleteHan-W5yVcSHXZoFQ      at Runtime.exports.handler (/var/task/index.js:102:13)     at processTicksAndRejections (internal/process/task_queues.js:97:5) (RequestId: c5cb4558-eedb-498e-a8a2-6c3052cd6db4)

Resource Name: pipelineawaiter-amplify-statapp-175824-containercdd4945e-service-statapi-8080 (AWS::CloudFormation::CustomResource)
Event Type: create
Reason: Received response status [FAILED] from custom resource. Message returned: The execution didn't succeed

Logs: /aws/lambda/amplify-statapp-dev-17582-AwaiterCustomCompleteHan-W5yVcSHXZoFQ

    at Runtime.exports.handler (/var/task/index.js:102:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) (RequestId: c5cb4558-eedb-498e-a8a2-6c3052cd6db4)

```

I can provide these logs if needed but there did not appear to be anything useful.

If I try to deploy with "Self Managed" (my preference) I get this different error:

```
CREATE_FAILED      ApiPipelinePipeline68596884                                             AWS::CodePipeline::Pipeline Wed Aug 25 2021 08:37:35 GMT-0600 (Mountain Daylight Time) 1 validation error detected: Value at 'pipeline.stages.1.member.actions.1.member.configuration' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 50000, Member must have length greater than or equal to 1] (Service: AWSCodePipeline; Status Code: 400; Error Code: ValidationException; Request ID: 9ed19d6d-1ca4-418e-be69-e896bd488cab; Proxy: null)

Resource Name: ApiPipelinePipeline68596884 (AWS::CodePipeline::Pipeline)
Event Type: create
Reason: 1 validation error detected: Value at 'pipeline.stages.1.member.actions.1.member.configuration' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 50000, Member must have length greater than or equal to 1] (Service: AWSCodePipeline; Status Code: 400; Error Code: ValidationException; Request ID: 9ed19d6d-1ca4-418e-be69-e896bd488cab; Proxy: null)

```

I have tried deploying really simple custom images from the public space. I also tried deploying the exact file from the issue reported link above. Same issues. And my custom image successfully deploys using Elastic Beanstalk. I love amplify and the power it brings and want to use it for my web app release. I either need a way for container deployments to work with custom images or I need to look at deploying and managing an API Gateway out side of amplify but using it in my Frontend (not preferred).  

FYI here is what my custom image Dockerfile looks like. The final command was ENTRYPOINT but I switched to CMD to see if that could've been the cause since all example Dockerfiles that were deploying used CMD.

```
FROM mcr.microsoft.com/dotnet/aspnet:5.0.9 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0.202 AS build
WORKDIR /src
COPY ["stat-api.csproj", "./"]
RUN dotnet restore "stat-api.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "stat-api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "stat-api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
CMD "dotnet" "stat-api.dll"

```

### Expected behavior

I expect to be able to deploy custom docker images hosted on ECR to an Amplify managed API. 

### Reproduction steps

1. Create a custom docker image with a reachable exposed endpoint. (In my case a .net 5 api)
2. Deploy this custom image to Amazon ECR
3. In a separate project run amplify init
4. Turn container deployment on with AWS Configure project 
5. Run amplify add api
6. Select Rest, Containers & Fully Managed or Self Managed
7. Paste in a dockerFile or dockercompose with Dockerfile all in the src (these should look like what I described in the bug description)
8. Run docker build or compose locally to test 
9. After successful local test run - amplify push
10. Observer error

### GraphQL schema(s)

Not Using GraphQL

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by OperationalFallacy** [comment]
I just run into this problem. There are couple of containers for PHP app: nginx and the app itself

App container is multi-stage build

```
FROM public.ecr.aws/docker/library/node:15.11.0-alpine3.13 as node
FROM public.ecr.aws/composer/composer:2.4.4-bin AS composer
FROM public.ecr.aws/docker/library/php:7.4-fpm-alpine
LABEL Description="Application container"
``` 

amplify push --profile ... produces this very helpful message

```
🛑 The following resources failed to deploy:
Resource Name: ApiPipelinePipeline68596884 (AWS::CodePipeline::Pipeline)
Event Type: create
Reason: 1 validation error detected: Value at 'pipeline.stages.1.member.actions.1.member.configuration' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 50000, Member must have length greater than or equal to 1] (Service: AWSCodePipeline; Status Code: 400; Error Code: ValidationException; Request ID: 20dab75a-9c13-4e2d-a58c-8f513fea3eb2; Proxy: null)

🛑 Resource is not in the state stackUpdateComplete
Name: ApiPipelinePipeline68596884 (AWS::CodePipeline::Pipeline), Event Type: create, Reason: 1 validation error detected: Value at 'pipeline.stages.1.member.actions.1.member.configuration' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 50000, Member must have length greater than or equal to 1] (Service: AWSCodePipeline; Status Code: 400; Error Code: ValidationException; Request ID: 20dab75a-9c13-4e2d-a58c-8f513fea3eb2; Proxy: null), IsCustomResource: false

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 86181475-8fde-44b2-9953-4a63b268769f
```

I don't even pretend to understand what it's trying to do. I see it's creating ECS resources, networking resource and... pipeline? So pipeline stack fails and it roll back everything. How do you even start troubleshooting this if cli designed to roll back all cloud formation on failure?

I have a question though, maybe somebody can help 
Is it worth pursuing building ECS-based API with Amplify?

We're deploying this app with front-end using CDK and it's working perfectly fine: a CDK Pipelines, with triggered builds, and so on. I wanted to separated and switch the API to Amplify, hoping that amplify with abstract nicely all the infra. Plus easy way to manage auth.

Yet that's exactly where it is not working with this 2.5 thousand lines cloud formation template.
