### ISSUE TITLE
Validation error deploying AmplifyGraphqlApi CDK construct 

### ISSUE THREAD

**Issue by japfohl** [aws-amplify/amplify-category-api#1946]
### How did you install the Amplify CLI?

N/A

### If applicable, what version of Node.js are you using?

18.18.0

### Amplify CLI Version

N/A

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

N/A - this bug has to do with the deployment of the newly released `AmplifyGraphqlApi` CDK construct.

### Describe the bug

I am following the walkthrough in the CDK construct announcement blog post found here: https://aws.amazon.com/blogs/mobile/announcing-aws-amplifys-graphql-api-cdk-construct-deploy-real-time-graphql-api-and-data-stack-on-aws/.  The only difference is I am deploying from a package in a `pnpm` monorepo, however, everything else is identical.  During the `cdk deploy` logs I see the following error message:

```
Error occurred while monitoring stack: Error [ValidationError]: 2 validation errors detected: Value '' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*; Value '' at 'stackName' failed to satisfy constraint: Member must have length greater than or equal to 1
    at Request.extractError (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:46430)
    at Request.callListeners (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:90083)
    at Request.emit (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:89531)
    at Request.emit (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:196289)
    at Request.transition (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:189841)
    at AcceptorStateMachine.runTo (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:154713)
    at C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:155043
    at Request.<anonymous> (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:190133)
    at Request.<anonymous> (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:196364)
    at Request.callListeners (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:90251) {
  code: 'ValidationError',
  time: 2023-10-12T14:16:28.072Z,
  requestId: 'e828bd70-e9db-4173-8924-3dec501fccf6',
  statusCode: 400,
  retryable: false,
  retryDelay: 142.81362092100824
}
```

Following deploy, the generated resources appear to work correctly. 

### Expected behavior

No errors during `cdk deploy`

### Reproduction steps

Follow instructions found here: https://aws.amazon.com/blogs/mobile/announcing-aws-amplifys-graphql-api-cdk-construct-deploy-real-time-graphql-api-and-data-stack-on-aws/

### Project Identifier

N/A

### Log output

<details>

```
# Put your logs below this line

C:\Project\Path > cdk deploy

✨  Synthesis time: 7.72s

BackendStack:  start: Building ###:current_account-current_region
BackendStack:  success: Built ###:current_account-current_region
BackendStack:  start: Publishing ###:current_account-current_region
BackendStack:  success: Published ###:current_account-current_region
This deployment will make potentially sensitive changes according to your current security approval level (--require-approval broadening).
Please confirm you intend to make the following modifications:

IAM Statement Changes
┌───┬────────────────────────────────────────────────────┬────────┬────────────────────────────────────────────────────┬──────────────────────────────────────────────────────┬───────────┐
│   │ Resource                                           │ Effect │ Action                                             │ Principal                                            │ Condition │
├───┼────────────────────────────────────────────────────┼────────┼────────────────────────────────────────────────────┼──────────────────────────────────────────────────────┼───────────┤
│ + │ ${Custom::CDKBucketDeployment########69AAFB │ Allow  │ sts:AssumeRole                                     │ Service:lambda.amazonaws.com                         │           │
│   │ 0CC9EB8756C/ServiceRole.Arn}                       │        │                                                    │                                                      │           │
├───┼────────────────────────────────────────────────────┼────────┼────────────────────────────────────────────────────┼──────────────────────────────────────────────────────┼───────────┤
│ + │ ${Custom::S3AutoDeleteObjectsCustomResourceProvide │ Allow  │ sts:AssumeRole                                     │ Service:lambda.amazonaws.com                         │           │
│   │ r/Role.Arn}                                        │        │                                                    │                                                      │           │
├───┼────────────────────────────────────────────────────┼────────┼────────────────────────────────────────────────────┼──────────────────────────────────────────────────────┼───────────┤
│ + │ ${NameApi/AmplifyCodegenAssets/AmplifyCodegenAssets │ Allow  │ s3:DeleteObject*                                   │ AWS:${Custom::S3AutoDeleteObjectsCustomResourceProvi │           │
│   │ Bucket.Arn}                                        │        │ s3:GetBucket*                                      │ der/Role.Arn}                                        │           │
│   │ ${NameApi/AmplifyCodegenAssets/AmplifyCodegenAssets │        │ s3:List*                                           │                                                      │           │
│   │ Bucket.Arn}/*                                      │        │ s3:PutBucketPolicy                                 │                                                      │           │
│ + │ ${NameApi/AmplifyCodegenAssets/AmplifyCodegenAssets │ Allow  │ s3:Abort*                                          │ AWS:${Custom::CDKBucketDeployment########69AA │           │
│   │ Bucket.Arn}                                        │        │ s3:DeleteObject*                                   │ #######/ServiceRole}                           │           │
│   │ ${NameApi/AmplifyCodegenAssets/AmplifyCodegenAssets │        │ s3:GetBucket*                                      │                                                      │           │
│   │ Bucket.Arn}/*                                      │        │ s3:GetObject*                                      │                                                      │           │
│   │                                                    │        │ s3:List*                                           │                                                      │           │
│   │                                                    │        │ s3:PutObject                                       │                                                      │           │
│   │                                                    │        │ s3:PutObjectLegalHold                              │                                                      │           │
│   │                                                    │        │ s3:PutObjectRetention                              │                                                      │           │
│   │                                                    │        │ s3:PutObjectTagging                                │                                                      │           │
│   │                                                    │        │ s3:PutObjectVersionTagging                         │                                                      │           │
├───┼────────────────────────────────────────────────────┼────────┼────────────────────────────────────────────────────┼──────────────────────────────────────────────────────┼───────────┤
│ + │ arn:${AWS::Partition}:s3:::{"Fn::Sub":"cdk-### │ Allow  │ s3:GetBucket*                                      │ AWS:${Custom::CDKBucketDeployment########69AA │           │
│   │ ds-assets-${AWS::AccountId}-${AWS::Region}"}       │        │ s3:GetObject*                                      │ #######/ServiceRole}                           │           │
│   │ arn:${AWS::Partition}:s3:::{"Fn::Sub":"cdk-### │        │ s3:List*                                           │                                                      │           │
│   │ ds-assets-${AWS::AccountId}-${AWS::Region}"}/*     │        │                                                    │                                                      │           │
└───┴────────────────────────────────────────────────────┴────────┴────────────────────────────────────────────────────┴──────────────────────────────────────────────────────┴───────────┘
IAM Policy Changes
┌───┬────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────┐
│   │ Resource                                                                   │ Managed Policy ARN                                                                           │
├───┼────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${Custom::CDKBucketDeployment########69AA#######/ServiceRole} │ arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole               │
├───┼────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${Custom::S3AutoDeleteObjectsCustomResourceProvider/Role}                  │ {"Fn::Sub":"arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"} │
└───┴────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Do you wish to deploy these changes (y/n)? y
BackendStack: deploying... [1/1]
BackendStack: creating CloudFormation changeset...
BackendStack |  0/17 | 10:15:56 AM | REVIEW_IN_PROGRESS   | AWS::CloudFormation::Stack  | BackendStack User Initiated
BackendStack |  0/17 | 10:16:02 AM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack  | BackendStack User Initiated
BackendStack |  0/17 | 10:16:06 AM | CREATE_IN_PROGRESS   | AWS::AppSync::GraphQLApi    | NameApi/GraphQLAPI (NameApiGraphQLAPI####) 
BackendStack |  0/17 | 10:16:06 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role              | Custom::S3AutoDeleteObjectsCustomResourceProvider/Role (CustomS3AutoDeleteObjectsCustomResourceProviderRole###) 
BackendStack |  0/17 | 10:16:06 AM | CREATE_IN_PROGRESS   | AWS::Lambda::LayerVersion   | NameApi/AmplifyCodegenAssets/AmplifyCodegenAssetsDeployment/AwsCliLayer (NameApiAmplifyCodegenAssetsAmplifyCodegenAssetsDeploymentAwsCliLayer###) 
BackendStack |  0/17 | 10:16:06 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role              | Custom::CDKBucketDeployment########69AA#######/ServiceRole (CustomCDKBucketDeployment########69AA#######ServiceRole###) 
BackendStack |  0/17 | 10:16:06 AM | CREATE_IN_PROGRESS   | AWS::CDK::Metadata          | NameApi/Blog/CDKMetadata/Default (CDKMetadata) 
BackendStack |  0/17 | 10:16:06 AM | CREATE_IN_PROGRESS   | AWS::S3::Bucket             | NameApi/AmplifyCodegenAssets/AmplifyCodegenAssetsBucket (NameApiAmplifyCodegenAssetsAmplifyCodegenAssetsBucket#####) 
BackendStack |  0/17 | 10:16:06 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role              | Custom::CDKBucketDeployment########69AA#######/ServiceRole (CustomCDKBucketDeployment########69AA#######ServiceRole###) Resource creation Initiated
BackendStack |  0/17 | 10:16:06 AM | CREATE_IN_PROGRESS   | AWS::IAM::Role              | Custom::S3AutoDeleteObjectsCustomResourceProvider/Role (CustomS3AutoDeleteObjectsCustomResourceProviderRole###) Resource creation Initiated
BackendStack |  0/17 | 10:16:06 AM | CREATE_IN_PROGRESS   | AWS::S3::Bucket             | NameApi/AmplifyCodegenAssets/AmplifyCodegenAssetsBucket (NameApiAmplifyCodegenAssetsAmplifyCodegenAssetsBucket#####) Resource creation Initiated
BackendStack |  0/17 | 10:16:07 AM | CREATE_IN_PROGRESS   | AWS::CDK::Metadata          | NameApi/Blog/CDKMetadata/Default (CDKMetadata) Resource creation Initiated
BackendStack |  1/17 | 10:16:07 AM | CREATE_COMPLETE      | AWS::CDK::Metadata          | NameApi/Blog/CDKMetadata/Default (CDKMetadata) 
BackendStack |  1/17 | 10:16:08 AM | CREATE_IN_PROGRESS   | AWS::AppSync::GraphQLApi    | NameApi/GraphQLAPI (NameApiGraphQLAPI####) Resource creation Initiated
BackendStack |  2/17 | 10:16:08 AM | CREATE_COMPLETE      | AWS::AppSync::GraphQLApi    | NameApi/GraphQLAPI (NameApiGraphQLAPI####) 
BackendStack |  2/17 | 10:16:09 AM | CREATE_IN_PROGRESS   | AWS::AppSync::GraphQLSchema | NameApi/GraphQLAPI/TransformerSchema (NameApiGraphQLAPITransformerSchema###) 
BackendStack |  2/17 | 10:16:09 AM | CREATE_IN_PROGRESS   | AWS::AppSync::ApiKey        | NameApi/GraphQLAPI/DefaultApiKey (NameApiGraphQLAPIDefaultApiKey###) 
BackendStack |  2/17 | 10:16:09 AM | CREATE_IN_PROGRESS   | AWS::AppSync::DataSource    | NameApi/GraphQLAPI/NONE_DS (NameApiGraphQLAPINONEDS######) 
BackendStack |  2/17 | 10:16:11 AM | CREATE_IN_PROGRESS   | AWS::AppSync::DataSource    | NameApi/GraphQLAPI/NONE_DS (NameApiGraphQLAPINONEDS######) Resource creation Initiated
BackendStack |  3/17 | 10:16:11 AM | CREATE_COMPLETE      | AWS::AppSync::DataSource    | NameApi/GraphQLAPI/NONE_DS (NameApiGraphQLAPINONEDS######) 
BackendStack |  3/17 | 10:16:11 AM | CREATE_IN_PROGRESS   | AWS::AppSync::ApiKey        | NameApi/GraphQLAPI/DefaultApiKey (NameApiGraphQLAPIDefaultApiKey###) Resource creation Initiated
BackendStack |  3/17 | 10:16:11 AM | CREATE_IN_PROGRESS   | AWS::AppSync::GraphQLSchema | NameApi/GraphQLAPI/TransformerSchema (NameApiGraphQLAPITransformerSchema###) Resource creation Initiated
BackendStack |  4/17 | 10:16:11 AM | CREATE_COMPLETE      | AWS::AppSync::ApiKey        | NameApi/GraphQLAPI/DefaultApiKey (NameApiGraphQLAPIDefaultApiKey###) 
BackendStack |  4/17 | 10:16:16 AM | CREATE_IN_PROGRESS   | AWS::Lambda::LayerVersion   | NameApi/AmplifyCodegenAssets/AmplifyCodegenAssetsDeployment/AwsCliLayer (NameApiAmplifyCodegenAssetsAmplifyCodegenAssetsDeploymentAwsCliLayer###) Resource creation Initiated
BackendStack |  5/17 | 10:16:16 AM | CREATE_COMPLETE      | AWS::Lambda::LayerVersion   | NameApi/AmplifyCodegenAssets/AmplifyCodegenAssetsDeployment/AwsCliLayer (NameApiAmplifyCodegenAssetsAmplifyCodegenAssetsDeploymentAwsCliLayer###) 
BackendStack |  6/17 | 10:16:22 AM | CREATE_COMPLETE      | AWS::IAM::Role              | Custom::CDKBucketDeployment########69AA#######/ServiceRole (CustomCDKBucketDeployment########69AA#######ServiceRole###) 
BackendStack |  7/17 | 10:16:22 AM | CREATE_COMPLETE      | AWS::IAM::Role              | Custom::S3AutoDeleteObjectsCustomResourceProvider/Role (CustomS3AutoDeleteObjectsCustomResourceProviderRole###) 
BackendStack |  8/17 | 10:16:22 AM | CREATE_COMPLETE      | AWS::AppSync::GraphQLSchema | NameApi/GraphQLAPI/TransformerSchema (NameApiGraphQLAPITransformerSchema###)
BackendStack-NameApiBlogNestedStackBlogNestedStackResource##### |  8/17 | 10:16:23 AM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack  | BackendStack-NameApiBlogNestedStackBlogNestedStackResource##### User Initiated
Error occurred while monitoring stack: Error [ValidationError]: 2 validation errors detected: Value '' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*; Value '' at 'stackName' failed to satisfy constraint: Member must have length greater than or equal to 1
    at Request.extractError (C:\...\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:46430)
    at Request.callListeners (C:\...\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:90083)
    at Request.emit (C:\...\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:89531)
    at Request.emit (C:\...\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:196289)
    at Request.transition (C:\...\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:189841)
    at AcceptorStateMachine.runTo (C:\...\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:154713)
    at C:\...\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:155043
    at Request.<anonymous> (C:\...\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:190133)
    at Request.<anonymous> (C:\...\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:196364)
    at Request.callListeners (C:\...\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:90251) {
  code: 'ValidationError',
  time: 2023-10-12T14:16:28.072Z,
  requestId: '##########',
  statusCode: 400,
  retryable: false,
  retryDelay: 142.81362092100824
}
BackendStack |  8/17 | 10:16:28 AM | CREATE_IN_PROGRESS   | AWS::Lambda::Function       | Custom::S3AutoDeleteObjectsCustomResourceProvider/Handler (CustomS3AutoDeleteObjectsCustomResourceProviderHandler###) 
BackendStack |  8/17 | 10:16:28 AM | CREATE_IN_PROGRESS   | AWS::IAM::Policy            | Custom::CDKBucketDeployment########69AA#######/ServiceRole/DefaultPolicy (CustomCDKBucketDeployment########69AA#######ServiceRoleDefaultPolicy#####)
BackendStack |  8/17 | 10:16:29 AM | CREATE_IN_PROGRESS   | AWS::S3::BucketPolicy       | NameApi/AmplifyCodegenAssets/AmplifyCodegenAssetsBucket/Policy (NameApiAmplifyCodegenAssetsAmplifyCodegenAssetsBucketPolicy########)
BackendStack |  8/17 | 10:16:29 AM | CREATE_IN_PROGRESS   | AWS::IAM::Policy            | Custom::CDKBucketDeployment########69AA#######/ServiceRole/DefaultPolicy (CustomCDKBucketDeployment########69AA#######ServiceRoleDefaultPolicy#####) Resource creation Initiated
BackendStack |  8/17 | 10:16:29 AM | CREATE_IN_PROGRESS   | AWS::Lambda::Function       | Custom::S3AutoDeleteObjectsCustomResourceProvider/Handler (CustomS3AutoDeleteObjectsCustomResourceProviderHandler###) Resource creation Initiated
BackendStack |  8/17 | 10:16:30 AM | CREATE_IN_PROGRESS   | AWS::S3::BucketPolicy       | NameApi/AmplifyCodegenAssets/AmplifyCodegenAssetsBucket/Policy (NameApiAmplifyCodegenAssetsAmplifyCodegenAssetsBucketPolicy########) Resource creation Initiated
BackendStack |  9/17 | 10:16:31 AM | CREATE_COMPLETE      | AWS::S3::BucketPolicy       | NameApi/AmplifyCodegenAssets/AmplifyCodegenAssetsBucket/Policy (NameApiAmplifyCodegenAssetsAmplifyCodegenAssetsBucketPolicy########)
BackendStack | 10/17 | 10:16:35 AM | CREATE_COMPLETE      | AWS::Lambda::Function       | Custom::S3AutoDeleteObjectsCustomResourceProvider/Handler (CustomS3AutoDeleteObjectsCustomResourceProviderHandler###)      
BackendStack | 10/17 | 10:16:36 AM | CREATE_IN_PROGRESS   | Custom::S3AutoDeleteObjects | NameApi/AmplifyCodegenAssets/AmplifyCodegenAssetsBucket/AutoDeleteObjectsCustomResource/Default (NameApiAmplifyCodegenAssetsAmplifyCodegenAssetsBucketAutoDeleteObjectsCustomResource########)
BackendStack | 10/17 | 10:16:38 AM | CREATE_IN_PROGRESS   | Custom::S3AutoDeleteObjects | NameApi/AmplifyCodegenAssets/AmplifyCodegenAssetsBucket/AutoDeleteObjectsCustomResource/Default (NameApiAmplifyCodegenAssetsAmplifyCodegenAssetsBucketAutoDeleteObjectsCustomResource########) Resource creation Initiated
BackendStack | 11/17 | 10:16:38 AM | CREATE_COMPLETE      | Custom::S3AutoDeleteObjects | NameApi/AmplifyCodegenAssets/AmplifyCodegenAssetsBucket/AutoDeleteObjectsCustomResource/Default (NameApiAmplifyCodegenAssetsAmplifyCodegenAssetsBucketAutoDeleteObjectsCustomResource########)
BackendStack | 12/17 | 10:16:45 AM | CREATE_COMPLETE      | AWS::IAM::Policy            | Custom::CDKBucketDeployment########69AA#######/ServiceRole/DefaultPolicy (CustomCDKBucketDeployment########69AA#######ServiceRoleDefaultPolicy#####)
BackendStack | 12/17 | 10:16:45 AM | CREATE_IN_PROGRESS   | AWS::Lambda::Function       | Custom::CDKBucketDeployment########69AA####### (CustomCDKBucketDeployment########69AA#######81C01536) 
BackendStack | 12/17 | 10:16:52 AM | CREATE_IN_PROGRESS   | AWS::Lambda::Function       | Custom::CDKBucketDeployment########69AA####### (CustomCDKBucketDeployment########69AA#######81C01536) Resource creation Initiated
BackendStack | 13/17 | 10:16:58 AM | CREATE_COMPLETE      | AWS::Lambda::Function       | Custom::CDKBucketDeployment########69AA####### (CustomCDKBucketDeployment########69AA#######81C01536) 
BackendStack | 13/17 | 10:16:59 AM | CREATE_IN_PROGRESS   | Custom::CDKBucketDeployment | NameApi/AmplifyCodegenAssets/AmplifyCodegenAssetsDeployment/CustomResource/Default (NameApiAmplifyCodegenAssetsAmplifyCodegenAssetsDeploymentCustomResource###)
BackendStack | 14/17 | 10:17:11 AM | CREATE_COMPLETE      | AWS::CloudFormation::Stack  | NameApi/Blog.NestedStack/Blog.NestedStackResource (NameApiBlogNestedStackBlogNestedStackResource##### 
14/17 Currently in progress: BackendStack, NameApiAmplifyCodegenAssetsAmplifyCodegenAssetsBucket#####, BackendStack-NameApiBlogNestedStackBlogNestedStackResource#####, NameApiAmplifyCodegenAssetsAmplifyCodegenAssetsDeploymentCustomResource###
BackendStack | 14/17 | 10:17:45 AM | CREATE_IN_PROGRESS   | Custom::CDKBucketDeployment | NameApi/AmplifyCodegenAssets/AmplifyCodegenAssetsDeployment/CustomResource/Default (NameApiAmplifyCodegenAssetsAmplifyCodegenAssetsDeploymentCustomResource###) Resource creation Initiated
BackendStack | 15/17 | 10:17:45 AM | CREATE_COMPLETE      | Custom::CDKBucketDeployment | NameApi/AmplifyCodegenAssets/AmplifyCodegenAssetsDeployment/CustomResource/Default (NameApiAmplifyCodegenAssetsAmplifyCodegenAssetsDeploymentCustomResource###)
BackendStack | 16/17 | 10:17:47 AM | CREATE_COMPLETE      | AWS::CloudFormation::Stack  | BackendStack
```

</details>

### Additional information

I

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by renebrandel** [comment]
Hi @japfohl - we're on this issue. It seems to be an incorrectly labeled "warning". The deployments do go through. Let us dig in further.

**Comment by AnilMaktala** [comment]
Hey @japfohl, We have created [this issue]( https://github.com/aws/aws-cdk/issues/27526) on CDK repo for better assistance. Please subscribe to receive future updates on [this issue]( https://github.com/aws/aws-cdk/issues/27526).
