### ISSUE TITLE
@aws-amplify/graphql-api-construct  ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by ThomasP1988** [aws-amplify/amplify-category-api#1976]
### How did you install the Amplify CLI?

yarn add @aws-amplify/graphql-api-construct

### If applicable, what version of Node.js are you using?

v20.7.0

### Amplify CLI Version

12.7.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

when doing cdk deploy, I get this error:

`Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/tom/Projects/theproject/infra/node_modules/@aws-amplify/backend-output-storage/lib/index.js from /Users/tom/Projects/theproject/infra/node_modules/@aws-amplify/graphql-api-construct/lib/amplify-graphql-api.js not supported.
Instead change the require of index.js in /Users/tom/Projects/theproject/infra/node_modules/@aws-amplify/graphql-api-construct/lib/amplify-graphql-api.js to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/Users/tom/Projects/theproject/infra/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/Users/tom/Projects/theproject/infra/node_modules/@aws-amplify/graphql-api-construct/lib/amplify-graphql-api.js:10:34)
    at require.extensions.<computed> [as .js] (/Users/tom/Projects/theproject/infra/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/Users/tom/Projects/theproject/infra/node_modules/@aws-amplify/graphql-api-construct/lib/index.js:4:29)
    at require.extensions.<computed> [as .js] (/Users/tom/Projects/theproject/infra/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/Users/tom/Projects/theproject/infra/aws/lib/graphql-stack.ts:6:33)
    at m._compile (/Users/tom/Projects/theproject/infra/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/tom/Projects/theproject/infra/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/Users/tom/Projects/theproject/infra/aws/bin/aws.ts:9:25)
    at m._compile (/Users/tom/Projects/theproject/infra/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/tom/Projects/theproject/infra/node_modules/ts-node/dist/index.js:859:16)
    at phase4 (/Users/tom/Projects/theproject/infra/node_modules/ts-node/dist/bin.js:466:20)
    at bootstrap (/Users/tom/Projects/theproject/infra/node_modules/ts-node/dist/bin.js:54:12)
    at main (/Users/tom/Projects/theproject/infra/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/Users/tom/Projects/theproject/infra/node_modules/ts-node/dist/bin.js:579:5) {
  code: 'ERR_REQUIRE_ESM'
}`

### Expected behavior

Not having this error

### Reproduction steps

1. import { AmplifyGraphqlApi, AmplifyGraphqlDefinition } from "@aws-amplify/graphql-api-construct";
2. cdk deploy

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hey @ThomasP1988, Thank you for bringing this up. Could you please share the `backend-stack.ts` file so that we can gain a better understanding and provide the necessary solutions?

**Comment by ThomasP1988** [comment]
I'm not sure which file you are talking about, do you want to see the way i set the construct in my stack? 
If that's the case then there it is:
`import { Stack, StackProps } from "aws-cdk-lib";
import { SetResourceName, Stages } from "configs";
import { Construct } from "constructs";
import { AmplifyGraphqlApi, AmplifyGraphqlDefinition } from "@aws-amplify/graphql-api-construct";
import { UserPool } from "aws-cdk-lib/aws-cognito";

export class GraphQLStack extends Stack {
    constructor(scope: Construct, id: string, props: StackProps & {
        stage: Stages;
        userPool: UserPool;
    }) {
        super(scope, id, props);
        const { stage, userPool } = props;

        const  amplify = new AmplifyGraphqlApi(this, SetResourceName(stage, "graphql"), {
            apiName: SetResourceName(stage, "graphql"),
            definition: AmplifyGraphqlDefinition.fromFiles(...["../../../back-end/graphql/schema/chat.gql"]),
            authorizationModes: {
                defaultAuthorizationMode: "AMAZON_COGNITO_USER_POOLS",
                userPoolConfig: {
                    userPool,
                },
                adminRoles: [] // can find where this role was defined, might have to create another in the future "${env}-GptFox-ChatAdminRoleName"
            },
            conflictResolution: {
                project: {
                    detectionType: "VERSION",
                    handlerType: "AUTOMERGE",
                }
            },
        });

        console.log(amplify.resources.tables)
    }
}`

My investigation led to the fact that you are compiling @aws-amplify/graphql-api-construct in commonjs, which require()
 your other librairies in "type" : "module", which is forbidden. You should:
 1. compile in esm
 2. compile in both: esm and cjs

**Comment by ThomasP1988** [comment]
reproduction steps: (i use yarn workspace yarn@3.6.3)
in a new package:
cdk init app --language typescript
yarn add @aws-amplify/graphql-api-construct

in the stack file:
import { AmplifyGraphqlApi } from "@aws-amplify/graphql-api-construct";
console.log("AuthorizationModes", AmplifyGraphqlApi);

then: 
cdk deploy

result: ERR_REQUIRE_ESM

**Comment by ThomasP1988** [comment]
I found a fix, thanks to your newly released package which isnt type: module

Put this in your root package.json
```
"resolutions": {
    "@aws-amplify/backend-output-storage": "0.2.0-alpha.4"
 },
```

**Comment by AnilMaktala** [comment]
Hi @ThomasP1988, Thank you for supplying the extra information and the resolution to address this matter. May we now consider closing this issue since it has been resolved?

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed as it is resolved. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
