### ISSUE TITLE
@aws-amplify/graphql-api-construct   call stack size exceeded in Lodash.js

### ISSUE THREAD

**Issue by jimjiminyjimjim** [aws-amplify/amplify-category-api#1978]
### How did you install the Amplify CLI?

yarn add @aws-amplify/graphql-api-construct

### If applicable, what version of Node.js are you using?

v18.14.2

### Amplify CLI Version

12.2.5

### What operating system are you using?

Mac 14.0

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I get the following error while building my schema with the new cdk construct:

`/Users/jimjiminyjimjim/web_projects/amplifyCDK/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:6598
      return nativeObjectToString.call(value);
                                  ^
RangeError: Maximum call stack size exceeded
    at Token.toString (<anonymous>)
    at objectToString (/Users/jimjiminyjimjim/web_projects/amplifyCDK/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:6598:35)
    at baseGetTag (/Users/jimjiminyjimjim/web_projects/amplifyCDK/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:3111:11)
    at baseClone (/Users/jimjiminyjimjim/web_projects/amplifyCDK/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:2684:19)
    at /Users/jimjiminyjimjim/web_projects/amplifyCDK/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:2733:34
    at arrayEach (/Users/jimjiminyjimjim/web_projects/amplifyCDK/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:530:11)
    at baseClone (/Users/jimjiminyjimjim/web_projects/amplifyCDK/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:2727:7)
    at /Users/jimjiminyjimjim/web_projects/amplifyCDK/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:2733:34
    at arrayEach (/Users/jimjiminyjimjim/web_projects/amplifyCDK/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:530:11)
    at baseClone (/Users/jimjiminyjimjim/web_projects/amplifyCDK/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:2727:7)
    `

if I remove this part of the schema, it seems to be fine:

`type PlanOutput {
  key: String
  value: String
  label: String
  public: Boolean
  displayString: String
}

type PostCodeLookupResults {
  items: [AddressPublic]
}

type AddressPublic {
  address1: String
  address2: String
  address3: String
  city: String
  postCode: String
  country: String
  formattedAddress: String
}

type Query {
  calculatePlan(planFormat: ID, skus: [String!]): [PlanOutput]
    @function(name: "calculatePlan")
    @auth(
      rules: [
        { allow: groups, groups:["admin"]}
        { allow: public }
        { allow: private, provider: iam }
      ]
  )
  postCodeLookup(postCode: String!): PostCodeLookupResults
    @function(name: "postcodeLookup")
    @auth(rules: [
        { allow: groups, groups:["admin"]}
        { allow: public }
      ]
    )
}`

And on closer inspection removing the  { allow: groups, groups:["admin"]}  lines seems to let it build.

I'm using the   { allow: groups, groups:["admin"]} in lots of other parts of my schema so not sure its specifically that.

The schema is 579 lines long. I've tried splitting into multiple files and actually the chunk of schema above builds absolutely fine in isolation, so doesn't seem to be syntax issues. But together with everything else, feels like its too long, or something else is causing the issue.

Also - schema builds find using Amplify CLI

### Expected behavior

Schema should build correctly.

### Reproduction steps

import { AmplifyGraphqlApi, AmplifyGraphqlDefinition } from "@aws-amplify/graphql-api-construct";
use schema.graphql as the AmplfyGraphqlDefinitiion
cdk deploy

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by phani-srikar** [comment]
Hi @jimjiminyjimjim, is it possible to share your full schema? You can also send us your project information by using `amplify diagnose --send-report` and providing us the identifier that gets generated.

**Comment by AnilMaktala** [comment]
Hi @jimjiminyjimjim, Thanks for sharing the stack file and schema. We are able to replicate the issue by using the provided schema. Hence, marking this as a bug for the team to evaluate further.

<img width="1101" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/dd1e653c-4759-4c48-b2c3-d4005afcce16">

**Comment by jimjiminyjimjim** [comment]
That's great - thanks for looking into this @AnilMaktala

**Comment by omer-nagar** [comment]
Im getting the same error.

**Comment by omer-nagar** [comment]
@phani-srikar @AnilMaktala 


I edited my schema to make it smaller - I still get the error - here is a sample 
note - that if I run with a very small schema I don't get any error, furthermore the same schema file that fails with `cdk dynth` / `cdk deploy` runs through `amplify api add` 

[schema_sample.txt](https://github.com/aws-amplify/amplify-category-api/files/13304127/schema_sample.txt)

```
/Users/omernagar/Documents/Projects/cvix/cvix-web/cvix_react_app/server/cdk-typescript/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:2392
    function stackSet(key, value) {
                     ^
RangeError: Maximum call stack size exceeded
    at Stack.stackSet [as set] (/Users/omernagar/Documents/Projects/cvix/cvix-web/cvix_react_app/server/cdk-typescript/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:2392:22)
    at baseClone (/Users/omernagar/Documents/Projects/cvix/cvix-web/cvix_react_app/server/cdk-typescript/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:2710:13)
    at /Users/omernagar/Documents/Projects/cvix/cvix-web/cvix_react_app/server/cdk-typescript/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:2733:34
    at arrayEach (/Users/omernagar/Documents/Projects/cvix/cvix-web/cvix_react_app/server/cdk-typescript/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:530:11)
    at baseClone (/Users/omernagar/Documents/Projects/cvix/cvix-web/cvix_react_app/server/cdk-typescript/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:2727:7)
    at /Users/omernagar/Documents/Projects/cvix/cvix-web/cvix_react_app/server/cdk-typescript/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:2733:34
    at arrayEach (/Users/omernagar/Documents/Projects/cvix/cvix-web/cvix_react_app/server/cdk-typescript/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:530:11)
    at baseClone (/Users/omernagar/Documents/Projects/cvix/cvix-web/cvix_react_app/server/cdk-typescript/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:2727:7)
    at /Users/omernagar/Documents/Projects/cvix/cvix-web/cvix_react_app/server/cdk-typescript/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:2733:34
    at arrayEach (/Users/omernagar/Documents/Projects/cvix/cvix-web/cvix_react_app/server/cdk-typescript/node_modules/@aws-amplify/graphql-api-construct/node_modules/lodash/lodash.js:530:11)
Waiting for the debugger to disconnect...
```

node version 20.8.1
@ aws-amplify/graphql-api-construct version 1.3.0
cdk version 2.104.0

**Comment by alex-vladut** [comment]
If it helps, I applied the following patch and it seems to fix the issue:

```diff
diff --git a/node_modules/@aws-amplify/graphql-api-construct/node_modules/@aws-amplify/graphql-transformer-core/lib/utils/directive-wrapper.js b/node_modules/@aws-amplify/graphql-api-construct/node_modules/@aws-amplify/graphql-transformer-core/lib/utils/directive-wrapper.js
index b6e565d..4e32506 100644
--- a/node_modules/@aws-amplify/graphql-api-construct/node_modules/@aws-amplify/graphql-transformer-core/lib/utils/directive-wrapper.js
+++ b/node_modules/@aws-amplify/graphql-api-construct/node_modules/@aws-amplify/graphql-transformer-core/lib/utils/directive-wrapper.js
@@ -37,7 +37,7 @@ class DirectiveWrapper {
                 [arg.name.value]: (0, graphql_1.valueFromASTUntyped)(arg.value),
             }), {});
             if (options === null || options === void 0 ? void 0 : options.deepMergeArguments) {
-                return lodash_1.default.merge(lodash_1.default.cloneDeep(defaultValue), argValues);
+                return lodash_1.default.merge({...defaultValue}, argValues);
             }
             return Object.assign(defaultValue, argValues);
         };
```

**Comment by phani-srikar** [comment]
Hi @jimjiminyjimjim, @alex-vladut, @omer-nagar, you can turn off the deep cloning of directive arguments by setting the following parameters while instantiating the `AmplifyGraphqlApi` construct:
```
translationBehavior: {
    shouldDeepMergeDirectiveConfigDefaults: false,
}
```
I've tested with the sample schema you've provided (thanks for that!) that I am now able to build your schema.

**Comment by phani-srikar** [comment]
Hi. Please upgrade the version of GraphQL API CDK construct to `1.5.5` as this issue is addressed in that version.

**Comment by chrisbonifacio** [comment]
Closing this as the fix has been released!
