### ISSUE TITLE
Unable to pull backend

### ISSUE THREAD

**Issue by muratcali** [aws-amplify/amplify-category-api#2280]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.10.0

### Amplify CLI Version

12.10.1

### What operating system are you using?

MacOS 14.2.1

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

We are not able to pull the amplify backend. When we run the pull command with or without app ID it failes with error: `Failed to pull the backend` without any further information. This happens on all of the laptops of our developers. Even when we try to build the project in amplify it failes with the same error. So we are also not able to build and publish something on Amplify. Ive added the error log when we run the `amplify pull --appId *** --envName *** --debug` command. 

Deleting the Amplify folder doesnt solve the problem and when we run amplify init (with or without AppID) it doesnt recognise the backend. Also running `amplify pull --appId *** --envName *** --debug` in an empty folder doesnt work. Pulling new created environments works but pulling the existing one is not possible.

Looks like there is somewhere a bug which prevents us and AWS Amplify systems for pulling the backend from this environment.

Here a picture from the failed build:
<img width="2165" alt="AWS Build failed" src="https://github.com/aws-amplify/amplify-cli/assets/38989039/40c09b0b-6e6a-4ebd-afec-7b130dd033d6">

### Expected behavior

I expect the backend to be pulled from AWS Amplify. 

### Reproduction steps

1. Running `amplify pull --appId *** --envName *** --debug`
2. Returns with `Failed to pull the backend` on all devices + AWS Amplify build
3. Tried the same within an empty folder and amplify init resulted with same error.

### Log output

<details>

```
muratcaliskan@MacBook-Pro-van-Murat dashboard % amplify pull --appId *** --envName staging --debug
Opening link: https://eu-central-1.admin.amplifyapp.com/admin/***/staging/verify/?loginVersion=1
⠏ Confirm login in the browser or manually paste in your CLI login key:
Successfully received Amplify Studio tokens.
Amplify AppID found: ***. Amplify App name is: ***
Backend environment staging found in Amplify Console app: ***
? Choose your default editor: Visual Studio Code
✔ Choose the type of app that you're building · javascript
Please tell us about your project
? What javascript framework are you using react
? Source Directory Path:  src
? Distribution Directory Path: build
? Build Command:  npm run-script build
? Start Command: npm run-script start
🛑 Failed to pull the backend.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

PullBackendFault: Failed to pull the backend.
    at attachBackend (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:55:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:64:9)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

File at path: '/Users/muratcaliskan/Projects/dashboard/amplify/backend/auth/TenderTracer/parameters.json' does not exist
Error: File at path: '/Users/muratcaliskan/Projects/dashboard/amplify/backend/auth/TenderTracer/parameters.json' does not exist
    at JSONUtilities.readJson (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-cli-core/lib/jsonUtilities.js:44:19)
    at StateManager.getData (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-cli-core/lib/state-manager/stateManager.js:327:56)
    at StateManager.getResourceParametersJson (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-cli-core/lib/state-manager/stateManager.js:149:25)
    at ensureAmplifyMetaFrontendConfig (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/on-category-outputs-change.js:105:60)
    at AmplifyToolkit.onCategoryOutputsChange (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/on-category-outputs-change.js:46:53)
    at generateFiles (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend-steps/a40-generateFiles.js:63:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async attachBackend (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:49:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:64:9)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

Session Identifier: 10e95ec8-c591-44f7-80cc-ffa852f5b60f


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by phani-srikar** [comment]
Hi @muratcali, thanks for attaching the CFN log screenshot. I you see the bottom most `UPDATE_FAILED`, it points to a failure in the nested API stack. You would need to go to that stack and look for the failure reason in `events` tab. Can you share that with us, so we can see what exactly went wrong?
