### ISSUE TITLE
GraphQLAPIDefaultApiKey (AWS::AppSync::ApiKey), Event Type: update, Reason: API key not found:

### ISSUE THREAD

**Issue by squirrelhomie** [aws-amplify/amplify-category-api#2745]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.14.2

### Amplify CLI Version

12.12.5

### What operating system are you using?

Mac OS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Deleted App Sync API Key that was linked to my Amplify Project

### Describe the bug

I have accidentally deleted my App Sync API Key that was linked to my amplify project. I am now attempting to generate a fresh one. Per the documentation, I am adding the following to my `parameters.json` file:

`CreateAPIKey: 0` 

When I run `amplify push` it returns this error:

`GraphQLAPIDefaultApiKey (AWS::AppSync::ApiKey), Event Type: update, Reason: API key not found:`

even though the documentation states [here](https://docs.amplify.aws/gen1/react/tools/cli-legacy/config-params/#createapikey) that it will delete the existing API Key, so that I can then add `CreateAPIKey: 1` to generate a fresh one. 

I've tried `amplify pull --restore` and `amplify push --force` and many other different combinations. In the past for expired keys, I have deleted the `deployment-state.json` file in my S3 bucket, that is not currently showing up. Additionally, in other posts regarding this issue, it is recommended to remove `GraphQLAPIIdOutput` from the `backend-config.js` file. However, that key does not appear in my `backend-config.js`, but it does in `amplify-dependant-resources-ref.d.ts` 

There does not seem to be a clear way for me to generate a fresh api key for my amplify project. Please advice. 

### Expected behavior

Adding `CreateAPIKey: 0` to `parameters.json` and then running `amplify push` should remove the API Key. Then updating `CreateAPIKey: 1` in `parameters.json` and running `amplify push` should generate a fresh one. 

### Reproduction steps

1. Create amplify project
2. Delete api key from app sync
3. Add `CreateAPIKey: 0` to `parameters.json` 
4. Run `amplify push` 

### Log output

<details>

```
# Put your logs below this line

Embedded stack arn:aws:cloudformation:us-east-1::stack/stack-name was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to create: [api7XXXXXXXXXResponseXXXXXX, apiXXXXXXResponseXXXXXX]
```

</details>

### Additional information

My current cloudformation stack is in a `UPDATE_ROLLBACK_COMPLETE` state 

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by squirrelhomie** [comment]
Would it help the team here if I run `amplify diagnose --send-report` ?

**Comment by AnilMaktala** [comment]
Hi @squirrelhomie, please send the diagnosis report and will work on reproducing this issue today.

**Comment by squirrelhomie** [comment]
> Hi @squirrelhomie, please send the diagnosis report and will work on reproducing this issue today.

@AnilMaktala Thank you! I have run `amplify diagnose --send-report` 

Is it safe to share the project identifier here?

**Comment by AnilMaktala** [comment]
Yes , Please share the identifier.

**Comment by AnilMaktala** [comment]
Hey @squirrelhomie, Thanks for sharing the details. I was able to recreate the new API key by following these steps. Could you please try them and let me know if it resolves the issue?

1. Add `CreateAPIKey: 0` to `parameters.json`.
2. Run `amplify push`.
3. Once successful, update `CreateAPIKey: 1` in `parameters.json`.
4. Run `amplify push` again.

<img width="1272" alt="image" src="https://github.com/user-attachments/assets/223215f1-1b01-40f2-93ac-2b409859371b">


<img width="904" alt="image" src="https://github.com/user-attachments/assets/e191f729-64b1-45c2-83ec-a34f36f6b6b3">

**Comment by squirrelhomie** [comment]
> Hey @squirrelhomie, Thanks for sharing the details. I was able to recreate the new API key by following these steps. Could you please try them and let me know if it resolves the issue?
> 
> 1. Add `CreateAPIKey: 0` to `parameters.json`.
> 2. Run `amplify push`.
> 3. Once successful, update `CreateAPIKey: 1` in `parameters.json`.
> 4. Run `amplify push` again.
> 
> <img alt="image" width="1272" src="https://private-user-images.githubusercontent.com/3206171/356759316-223215f1-1b01-40f2-93ac-2b409859371b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTg1OTQsIm5iZiI6MTcyMzI5ODI5NCwicGF0aCI6Ii8zMjA2MTcxLzM1Njc1OTMxNi0yMjMyMTVmMS0xYjAxLTQwZjItOTNhYy0yYjQwOTg1OTM3MWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMTM1ODE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWZiODI1YmEyYzg2OTQ3MjBjMWZlMTk1NGZmMDE0MzdmMzRiYjQyMTM2MDczZTcyM2NmZjI0N2E4YzYzM2FhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.abL9gtUjUWp9s5AfUCZfCdi1GqLBzqgijwtyZzV_FJk"> <img alt="image" width="904" src="https://private-user-images.githubusercontent.com/3206171/356759385-e191f729-64b1-45c2-83ec-a34f36f6b6b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTg1OTQsIm5iZiI6MTcyMzI5ODI5NCwicGF0aCI6Ii8zMjA2MTcxLzM1Njc1OTM4NS1lMTkxZjcyOS02NGIxLTQ1YzItODNlYy1hMzRmMzZmNmI2YjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMTM1ODE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTIwNDAwOTlmNjQyODNhZmQ4MGUxNmZkZjg0NmUzMzdkZWVkZjQ1MWQ1ODE1Mjk1ZDA4NWRjM2FjZjllOTJkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.waRBDxg1hYpoXFlWizSzza9142Ys85U4JK81ltPijV8">

@AnilMaktala Running the steps you shared above returns this error for me when adding `--debug` 

```
DeploymentFault: Resource is not in the state stackUpdateComplete
    at Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/push-resources.js:362:11)
    at async /snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:137:16
    at async Promise.all (index 0)
    at async providersPush (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:133:5)
    at async AmplifyToolkit.pushResources (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/push-resources.js:107:13)
    at async Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:194:9)
    at async executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)

Resource is not in the state stackUpdateComplete
ResourceNotReady: Resource is not in the state stackUpdateComplete
    at constructor.setError (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/resource_waiter.js:182:47)
    at Request.CHECK_ACCEPTORS (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/resource_waiter.js:44:12)
    at Request.callListeners (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/amplify-cli/build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/snapshot/amplify-cli/build/node_modules/aws-sdk/lib/event_listeners.js:417:13)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by squirrelhomie** [comment]
@AnilMaktala Is there anything else I can do to help get this figured out? This is a complete show stopper for our project and we are over a week behind at this point.

**Comment by AnilMaktala** [comment]
Hey @squirrelhomie, Is Step 2 was successful for you?

**Comment by squirrelhomie** [comment]
@AnilMaktala No, I can not successfully run `amplify push` without receiving the errors shared above

**Comment by AnilMaktala** [comment]
@squirrelhomie Are you on Discord by any chance? It would be easier to connect there.

**Comment by squirrelhomie** [comment]
@AnilMaktala Yes, you can find me on discord under squirrelhomie. Would you like to move over to discord now?

**Comment by squirrelhomie** [comment]
@AnilMaktala After many attempts, I was finally able to get `amplify push` to work and generate a new API Key by first running it with `CreateAPIKey: 0` and then `CreateAPIKey: 1` However, I don't think my 'solution' was a _real_ solution. 

I had a test API in API Gateway set up that after running `amplify remove api <RESOURCE_NAME>` `amplify push` worked. But, it is unclear why this worked and why amplify is not set up to take whatever edge case this was in to account when generating a new api key. 

I have enjoyed using amplify and it has streamlined our development process a lot. But the process of generating a new API Key should be improved. I am lucky that the problematic API was not needed, but what if it was? Defintely causes some concerns once we get to production and we'll need to think if some kind of mitigation plan to reduce the risk of this happening once we're live. 

Thank you @AnilMaktala for all of your help on this!

**Comment by AnilMaktala** [comment]
Hey @squirrelhomie, Thank you for taking the time to collaborate and share your screen on this issue. Based on our discussion and the resolution, I will close this issue. If you need any further assistance, please feel free to comment here.
