### ISSUE TITLE
Aurora serverless Postgresql not supported

### ISSUE THREAD

**Issue by berenddeboer** [aws-amplify/amplify-category-api#351]
Running `amplify api add-graphql-datasource` will fetch my Aurora PostgreSQL cluster, then the secret, and then crashes:

```
? Select the secret used to access your Aurora Serverless cluster: RDSRootSecret
⠼ Fetching Aurora Serverless cluster...BadRequestException: FATAL: database "root" does not exist
    at Object.extractError (/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
There was an error adding the datasource
```
The reason is my database user is called `root` and there is no database `root`, it just has a different name.

What I would expect is that it does not switch to the postgresql default database (which is the name of the user), and continues to show me all my databases.

**Desktop**
- Amplify cli: 4.7.0
 - Ubuntu 19.10
 - Node Version: 10.18.0

**Comment by nathan-mill** [comment]
+1 for natively supporting literally any kind of persistence layer other than DynamoDB.

**Comment by renebrandel** [comment]
Hi folks - wanted to cross-post this RFC here:
- https://github.com/aws-amplify/amplify-category-api/issues/815

We are working on adding support for Postgres. The linked preview build allows you to import MySQL databases now. We plan on following the same pattern for Postgres. https://github.com/aws-amplify/amplify-category-api/issues/815#issuecomment-1758109259

**Comment by renebrandel** [comment]
Closing this as we've shipped support for this feature.
