### ISSUE TITLE
mutation fails

### ISSUE THREAD

**Issue by alonsnir** [aws-amplify/amplify-category-api#821]

**Comment by josefaidt** [comment]
Hey @alonsnir :wave: thanks for raising this! Do you experience similar issues when using the examples from [this doc](https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js/)?

**Comment by alonsnir** [comment]
@josefaidt I have a perfectly working application in region eu-central-1, now when I'm deploying it in ap-southeast-2 this happens. 

To answer your question, I didn't try examples from the doc deployed in ap-southeast-2, but in the other region, examples provided by the docs and more important, the actual application, all work.

**Comment by alonsnir** [comment]
@josefaidt any updates on this?
I have deleted the app completely and re-deployed everything - same error.

**Comment by josefaidt** [comment]
Hey @alonsnir thank you for the clarification and for hopping on office hours today! It was great chatting! While I work to set up a multi-region app deployment, would you mind confirming the AWS_REGION environment variable is set properly in your `ap-southeast-2` deployment?

**Comment by alonsnir** [comment]
Hi @josefaidt I'm not sure what environment do you mean. Could you clarify, please?
Here is the profile I have used for authentication
~/.aws/config
```
[profile sidney]
region=ap-southeast-2
output=json

```

**Comment by alonsnir** [comment]
@josefaidt just in case, added the following to the function code:

`console.log(AWS_DEFAULT_REGION: ${process.env.AWS_DEFAULT_REGION}, AWS_ACCESS_KEY: ${process.env.AWS_ACCESS_KEY}, AWS_ACCESS_KEY_ID: ${process.env.AWS_ACCESS_KEY_ID}, AWS_SECRET_ACCESS_KEY: ${process.env.AWS_SECRET_ACCESS_KEY}, AWS_SESSION_TOKEN: ${process.env.AWS_SESSION_TOKEN});
`

which resolves to:

```
2022-10-02T11:35:32.500Z	dfb0f95e-f5dc-57a8-818f-a2ed8c64de80	INFO	
AWS_DEFAULT_REGION: ap-southeast-2, 
AWS_ACCESS_KEY: undefined, 
AWS_ACCESS_KEY_ID: xxxxxxxx, 
AWS_SECRET_ACCESS_KEY: xxxxxxxxxx, 
AWS_SESSION_TOKEN: xxxxxxx

```

as shown here, AWS_ACCESS_KEY is undefined. I don't know if this indicates a potential problem.

**Comment by josefaidt** [comment]
Hey @alonsnir :wave: apologies for the confusion, I'm referring to the `AWS_REGION` environment variable set for the Lambda function in the environment that is deploying to `ap-southeast-2`

**Comment by alonsnir** [comment]
Hi @josefaidt, thanks for the clarification. 
I have added that info to the log. It's `ap-southeast-2`

```
2022-10-03T18:45:06.053Z	77fe56fc-642b-49f4-ad3e-80e863a2d5df	INFO	
AWS_REGION: ap-southeast-2, 
AWS_DEFAULT_REGION: ap-southeast-2, 
AWS_ACCESS_KEY: undefined, 
AWS_ACCESS_KEY_ID: xxxxxxxxx, 
AWS_SECRET_ACCESS_KEY: xxxxxxxxx, 
AWS_SESSION_TOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

```
Result obviously the same
`"result": {
            "errors": [
                {
                    "errorType": "BadRequestException",
                    "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/graphql\n\naccept:*/*\ncontent-type:application/json; charset=UTF-8\nhost:7a25xrr675gr7e2fpm447lvp24.appsync-api.ap-southeast-2.amazonaws.com\nx-amz-date:20221003T184506Z\nx-amz-security-token:xxxxxxxxxxx\naccept;content-type;host;x-amz-date;x-amz-security-token\nffe9e1deab1c3a5fbfe2315744bd7a7da80e8ec7477e20cc020395526d9a5f70'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20221003T184506Z\n20221003/ap-southeast-2/appsync/aws4_request\n7eb9cded1a81edae597f45bf657acc1da19f26f1eda84d45c919d7842be5bcda'\n"
                }
            ]
        }`

What do you think about `AWS_ACCESS_KEY: undefined`? Is that normal, expected?

**Comment by josefaidt** [comment]
> What do you think about AWS_ACCESS_KEY: undefined? Is that normal, expected?

Yes I believe the key will be `AWS_ACCESS_KEY_ID`. I did notice a small typo in the original post, may not be affecting this but I wanted to call it out 

```
credentials: AWSg.config.credentials
```

Do you experience the same issue when following the approach described in [this doc](https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js/)?

**Comment by alonsnir** [comment]
Hi @josefaidt 
AWSg is ok:
`const AWSg = require('aws-sdk/global');` 

as to the sample from the doc, it fails right away

```
amplify mock function myfunction --event src/event.json
Ensuring latest function changes are built...
Starting execution...
myfunction failed with the following error:
{
  stack: 'Error: Could not load lambda handler function due to SyntaxError: Cannot use import statement outside a module\n' +
    '    at loadHandler (/snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js:106:15)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
    '    at async invokeFunction (/snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js:61:27)\n' +
    '    at async process.<anonymous> (/snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js:32:24)',
  message: 'Could not load lambda handler function due to SyntaxError: Cannot use import statement outside a module'
}
Finished execution.
```

**Comment by josefaidt** [comment]
Hey @alonsnir here is an example of a GraphQL call from Nodejs using private IAM

```js
const { Sha256 } = require('@aws-crypto/sha256-js')
const { defaultProvider } = require('@aws-sdk/credential-provider-node')
const { SignatureV4 } = require('@aws-sdk/signature-v4')
const { HttpRequest } = require('@aws-sdk/protocol-http')
const { default: fetch, Request } = require('node-fetch')

const GRAPHQL_ENDPOINT = process.env.API_808_GRAPHQLAPIENDPOINTOUTPUT
const AWS_REGION = process.env.AWS_REGION || 'us-east-1'

const query = /* GraphQL */ `
  query LIST_TODOS {
    listTodos {
      items {
        id
        name
        description
      }
    }
  }
`

/**
 * @type {import('@types/aws-lambda').APIGatewayProxyHandler}
 */
exports.handler = async (event) => {
  console.log(`EVENT: ${JSON.stringify(event)}`)

  const endpoint = new URL(GRAPHQL_ENDPOINT)

  const signer = new SignatureV4({
    credentials: defaultProvider(),
    region: AWS_REGION,
    service: 'appsync',
    sha256: Sha256,
  })

  const requestToBeSigned = new HttpRequest({
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      host: endpoint.host,
    },
    hostname: endpoint.host,
    body: JSON.stringify({ query }),
    path: endpoint.pathname,
  })

  const signed = await signer.sign(requestToBeSigned)
  const request = new Request(endpoint, signed)

  let statusCode = 200
  let body
  let response

  try {
    response = await fetch(request)
    body = await response.json()
    if (body.errors) statusCode = 400
  } catch (error) {
    statusCode = 500
    body = {
      errors: [
        {
          message: error.message,
        },
      ],
    }
  }

  return {
    statusCode,
    body: JSON.stringify(body),
  }
}
```

I'll work to get our examples updated

**Comment by alonsnir** [comment]
Hi @josefaidt, still no luck:(
Followed the steps from from [the doc ](https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js/)(added a new function, configured `"type": "module"` and dependencies to the package.json). Then used the code snippet you have provided, and:

```
$ amplify mock function myfunction --event src/event.json
Ensuring latest function changes are built...
Starting execution...
myfunction failed with the following error:
{
  stack: 'Error: Could not load lambda handler function due to Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/alon/front-end/amplify/backend/function/myfunction/src/index.js\n' +
    'require() of ES modules is not supported.\n' +
    'require() of /home/alon/front-end/amplify/backend/function/myfunction/src/index.js from /snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.\n' +
    'Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/alon/front-end/amplify/backend/function/myfunction/src/package.json.\n' +
    '\n' +
    '    at loadHandler (/snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js:106:15)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
    '    at async invokeFunction (/snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js:61:27)\n' +
    '    at async process.<anonymous> (/snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js:32:24)',
  message: 'Could not load lambda handler function due to Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/alon/front-end/amplify/backend/function/myfunction/src/index.js\n' +
    'require() of ES modules is not supported.\n' +
    'require() of /home/alon/front-end/amplify/backend/function/myfunction/src/index.js from /snapshot/repo/build/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.\n' +
    'Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/alon/front-end/amplify/backend/function/myfunction/src/package.json.\n'
}
Finished execution.
```

**Comment by alonsnir** [comment]
@josefaidt 
after applying the "Two notes" you have mentioned [in this issue](https://github.com/aws-amplify/amplify-cli/issues/10432#issuecomment-1184647915) I was able to pass the authentication and run queries.
Now trying to adjust my mutation code.
